### ISSUE TITLE
Get "No service was found" while clicking sign in

### ISSUE THREAD

**Issue by sabinlald** [hlavki/g-suite-identity-sync#22]
I think i have configured as your documentation but i am still getting the issue .I am using 0.3.6 bu. I am not able to find why this is happening
 ```
identity_1  | 12:39:07.125 ERROR [Blueprint Extender: 2] Unable to start blueprint container for bundle eu.hlavki.identity.g-suite-identity-sync-services/0.3.6 due to unresolved dependencies [(objectClass=eu.hlavki.identity.services.ldap.LdapAccountService)]
identity_1  | java.util.concurrent.TimeoutException
identity_1  |   at org.apache.aries.blueprint.container.BlueprintContainerImpl$1.run(BlueprintContainerImpl.java:373)
identity_1  |   at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:45)
identity_1  |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
identity_1  |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
identity_1  |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
identity_1  |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
identity_1  |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
identity_1  |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
identity_1  |   at java.lang.Thread.run(Thread.java:748)
identity_1  | 12:39:11.245 ERROR [Blueprint Extender: 1] Unable to start blueprint container fodentity.g-suite-identity-sync-services-rest/0.3.6 due to unresolved dependencies [(objectClass=ervices.sync.AccountSyncService), (objectClass=eu.hlavki.identity.services.ldap.LdapAccountServ
identity_1  | java.util.concurrent.TimeoutException
identity_1  |   at org.apache.aries.blueprint.container.BlueprintContainerImpl$1.run(BlueprintC3)
identity_1  |   at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(Disc:45)
identity_1  |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
identity_1  |   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
identity_1  |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$oolExecutor.java:180)
identity_1  |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Schutor.java:293)
```

**Comment by hlavki** [comment]
thanks for report @sabinlald, but this information is not enought to figure it out. Can you send me full `karaf.log` to my email, which can be found in my profile.
You can use `docker cp` to obtain `/opt/karaf/data/log/karaf.log` file. thanks

**Comment by hlavki** [comment]
Closing this due to inactivity. Fee free to open new issue if you have any question.

**Comment by hlavki** [comment]
Please, don't use development versions. This version is not compatible with documentation. Thank you
