### ISSUE TITLE
Illegal character in path at index 83

### ISSUE THREAD

**Issue by hlavki** [hlavki/g-suite-identity-sync#77]
Getting error when adding account to LDAP.

```
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in path at index 83: https://lh3.googleusercontent.com/a-/AOh14GgPG0866eC-84EjXGai_LFUaqDnmWORLGe3jPvN1A\u003ds96-c
  at org.apache.cxf.jaxrs.impl.UriBuilderImpl.uri(UriBuilderImpl.java:966)
  at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:120)
  at eu.hlavki.identity.services.rest.service.UserInfoService.resizeProfilePicture(UserInfoService.java:38)
  at eu.hlavki.identity.services.rest.service.UserInfoService.getUserInfo(UserInfoService.java:30)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
  at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
  at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
  at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
  at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
  at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
  at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
  at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
  at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
  at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
  at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
  at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
  at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
  at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:296)
  at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:220)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
  at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:271)
  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
  at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
  at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
  at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1363)
  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:298)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1278)
  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:82)
  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  at org.eclipse.jetty.server.Server.handle(Server.java:500)
  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
  at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 83: https://lh3.googleusercontent.com/a-/AOh14GgPG0866eC-84EjXGai_LFUaqDnmWORLGe3jPvN1A\u003ds96-c
  at java.base/java.net.URI.create(Unknown Source)
  at org.apache.cxf.jaxrs.impl.UriBuilderImpl.uri(UriBuilderImpl.java:963)
  ... 62 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 83: https://lh3.googleusercontent.com/a-/AOh14GgPG0866eC-84EjXGai_LFUaqDnmWORLGe3jPvN1A\u003ds96-c
  at java.base/java.net.URI$Parser.fail(Unknown Source)
  at java.base/java.net.URI$Parser.checkChars(Unknown Source)
  at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
  at java.base/java.net.URI$Parser.parse(Unknown Source)
  at java.base/java.net.URI.<init>(Unknown Source)
  ... 64 more
```

**Comment by hlavki** [comment]
I don't know why, but Jettison does not unescape unicode characters. Fixed by dffca20a263866e0327cb27805135418d515b2a6
